import { Link } from "wouter";
import { ArrowLeft, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function AffiliateDisclaimer() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur">
        <div className="mx-auto max-w-7xl px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover-elevate rounded-md px-3 py-2 -ml-3" data-testid="link-logo-home">
            <Sparkles className="w-6 h-6 text-primary" />
            <span className="text-xl font-semibold">GenAIMagic.io</span>
          </Link>
          <Link href="/" data-testid="link-home">
            <Button variant="ghost" className="gap-2" data-testid="button-back-home-header">
              <ArrowLeft className="w-4 h-4" />
              Back Home
            </Button>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="text-4xl font-bold mb-4">Affiliate Disclaimer</h1>
        <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-4">Affiliate Relationships</h2>
            <p className="text-muted-foreground leading-relaxed">
              GenAIMagic is a content generation tool designed to help users create affiliate marketing content. Users of GenAIMagic may generate content that includes affiliate links to products and services for which they may receive compensation if purchases are made through those links.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">FTC Disclosure Requirements</h2>
            <p className="text-muted-foreground leading-relaxed">
              In accordance with the Federal Trade Commission (FTC) guidelines, users of GenAIMagic must disclose their affiliate relationships when publishing content generated by this tool. Users are solely responsible for ensuring their content includes proper affiliate disclosures as required by law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">User Responsibility</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              When using GenAIMagic to create affiliate content, users must:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Clearly and conspicuously disclose affiliate relationships to their audience</li>
              <li>Place disclosures near affiliate links in a manner that is easily noticeable</li>
              <li>Use clear language such as "This post contains affiliate links" or "I may earn a commission"</li>
              <li>Comply with all FTC guidelines and applicable laws regarding affiliate marketing</li>
              <li>Ensure disclosures are not hidden or obscured in any way</li>
              <li>Update disclosures as affiliate relationships change</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">No Endorsement of Products</h2>
            <p className="text-muted-foreground leading-relaxed">
              GenAIMagic does not endorse, recommend, or guarantee any products or services that users choose to promote using content generated by our tool. Product information is provided by users or scraped from external sources, and we do not verify its accuracy or quality.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Earnings Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              We make no guarantees regarding the income, earnings, or results users may achieve from using GenAIMagic to create affiliate content. Affiliate marketing success depends on many factors including product quality, audience engagement, marketing skills, and market conditions. Any earnings examples or testimonials are not representative of typical results.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Third-Party Affiliate Programs</h2>
            <p className="text-muted-foreground leading-relaxed">
              Users of GenAIMagic are responsible for complying with the terms and conditions of any third-party affiliate programs they participate in. We are not responsible for any issues, disputes, or terminations arising from users' relationships with affiliate programs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Accuracy of Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              Users must ensure that all product claims, prices, features, and other information included in their affiliate content is accurate and up-to-date. Making false or misleading claims about products may violate FTC guidelines and other consumer protection laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Recommendation Based on Experience</h2>
            <p className="text-muted-foreground leading-relaxed">
              The FTC requires that affiliate marketers only recommend products they have personally used or thoroughly researched. GenAIMagic is a tool that generates content based on user input, but users are responsible for ensuring they meet all legal requirements for endorsing and recommending products.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Disclosure Placement</h2>
            <p className="text-muted-foreground leading-relaxed">
              While GenAIMagic may generate content structures, users must manually add appropriate affiliate disclosures to their published content. Disclosures should be placed prominently at the beginning of content and, where appropriate, near specific affiliate links.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">International Compliance</h2>
            <p className="text-muted-foreground leading-relaxed">
              Users operating outside the United States must also comply with their local laws and regulations regarding affiliate marketing, advertising disclosures, and consumer protection. This may include GDPR in the European Union, ASA guidelines in the UK, or other applicable regulations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Changes to This Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update this Affiliate Disclaimer from time to time to reflect changes in laws, regulations, or our practices. Users should review this disclaimer periodically.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions about affiliate marketing compliance or this disclaimer, please consult with a legal professional and contact us through our website for tool-related questions.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t">
          <Link href="/" data-testid="link-back-home">
            <Button variant="outline" className="gap-2" data-testid="button-back-home">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
