import { Link } from "wouter";
import { ArrowLeft, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur">
        <div className="mx-auto max-w-7xl px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover-elevate rounded-md px-3 py-2 -ml-3" data-testid="link-logo-home">
            <Sparkles className="w-6 h-6 text-primary" />
            <span className="text-xl font-semibold">GenAIMagic.io</span>
          </Link>
          <Link href="/" data-testid="link-home">
            <Button variant="ghost" className="gap-2" data-testid="button-back-home-header">
              <ArrowLeft className="w-4 h-4" />
              Back Home
            </Button>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="text-4xl font-bold mb-4">Disclaimer</h1>
        <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-4">General Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              The information provided by GenAIMagic ("we," "us," or "our") is for general informational purposes only. All information generated by our AI-powered service is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information generated by the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">
              GenAIMagic uses artificial intelligence to generate content based on user inputs. AI-generated content may contain errors, inaccuracies, outdated information, or biases. The content is not intended to replace professional advice, research, or human judgment. Users must review, fact-check, and verify all AI-generated content before using it for any purpose.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">No Professional Advice</h2>
            <p className="text-muted-foreground leading-relaxed">
              The content generated by GenAIMagic does not constitute professional advice of any kind, including but not limited to legal, financial, medical, or business advice. You should consult with appropriate professionals before making any decisions based on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">External Links</h2>
            <p className="text-muted-foreground leading-relaxed">
              GenAIMagic may process URLs and external content provided by users. We have no control over the nature, content, and availability of those external sites. The inclusion or processing of any links does not necessarily imply a recommendation or endorse the views expressed within them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of GenAIMagic or reliance on any information generated by the service. Your use of the service and your reliance on any AI-generated content is solely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Accuracy of Product Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              We do not verify the accuracy of product information, prices, features, or claims that users input into the system or that are scraped from external sources. Users are responsible for ensuring that all product information is accurate, up-to-date, and compliant with applicable laws and regulations before publishing content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Third-Party Services</h2>
            <p className="text-muted-foreground leading-relaxed">
              GenAIMagic uses our GenAiMagic trained AI Agent (powered by Google's AI infrastructure) to generate content. We are not responsible for any issues, errors, or problems arising from the use of third-party AI services. Users should review Google's terms of service and privacy policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">No Guarantee of Results</h2>
            <p className="text-muted-foreground leading-relaxed">
              We make no guarantees regarding the effectiveness, SEO performance, conversion rates, or any other outcomes from content generated using GenAIMagic. Success in affiliate marketing depends on many factors beyond the content itself.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Copyright and Plagiarism</h2>
            <p className="text-muted-foreground leading-relaxed">
              While GenAIMagic generates original content, we cannot guarantee that AI-generated content will always be completely unique or free from unintentional similarities to existing content. Users are responsible for checking generated content for plagiarism and ensuring it does not infringe on any copyrights before publication.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Changes to This Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify this disclaimer at any time. Any changes will be effective immediately upon posting to this page. Your continued use of the service after such modifications constitutes acceptance of the updated disclaimer.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about this disclaimer, please contact us through our website.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t">
          <Link href="/" data-testid="link-back-home">
            <Button variant="outline" className="gap-2" data-testid="button-back-home">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
