import { Link } from "wouter";
import { ArrowLeft, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur">
        <div className="mx-auto max-w-7xl px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 hover-elevate rounded-md px-3 py-2 -ml-3" data-testid="link-logo-home">
            <Sparkles className="w-6 h-6 text-primary" />
            <span className="text-xl font-semibold">GenAIMagic.io</span>
          </Link>
          <Link href="/" data-testid="link-home">
            <Button variant="ghost" className="gap-2" data-testid="button-back-home-header">
              <ArrowLeft className="w-4 h-4" />
              Back Home
            </Button>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="text-4xl font-bold mb-4">Terms of Use</h1>
        <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-4">Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing and using GenAIMagic, you accept and agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Service Description</h2>
            <p className="text-muted-foreground leading-relaxed">
              GenAIMagic is an AI-powered content generation tool that creates SEO-optimized affiliate blog content based on user-provided product information and research materials. The service uses our GenAiMagic trained AI Agent to generate content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">User Responsibilities</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              As a user of GenAIMagic, you agree to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Provide accurate and lawful information when using the service</li>
              <li>Not use the service for any illegal or unauthorized purpose</li>
              <li>Review and edit AI-generated content before publishing</li>
              <li>Ensure compliance with FTC guidelines for affiliate marketing</li>
              <li>Not attempt to reverse engineer or compromise the service</li>
              <li>Respect intellectual property rights of others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Content Ownership and Rights</h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain ownership of the content you generate using GenAIMagic. However, you are solely responsible for ensuring that the generated content complies with all applicable laws, regulations, and third-party rights before publishing or distributing it.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">AI-Generated Content Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              Content generated by GenAIMagic is created by artificial intelligence and may contain errors, inaccuracies, or biases. You are responsible for reviewing, fact-checking, and editing all generated content before use. We do not guarantee the accuracy, completeness, or quality of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Service Availability</h2>
            <p className="text-muted-foreground leading-relaxed">
              We strive to maintain high availability but do not guarantee uninterrupted access to the service. We reserve the right to modify, suspend, or discontinue the service at any time without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, GenAIMagic and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Indemnification</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to indemnify and hold harmless GenAIMagic and its operators from any claims, damages, or expenses arising from your use of the service or violation of these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Modifications to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify these Terms of Use at any time. Your continued use of the service after changes are posted constitutes acceptance of the modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms of Use shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Use, please contact us through our website.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t">
          <Link href="/" data-testid="link-back-home">
            <Button variant="outline" className="gap-2" data-testid="button-back-home">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
